import Head from "next/head";
import Image from "next/image";
import {
  AppBar,
  Avatar,
  Button,
  IconButton,
  Toolbar,
  Typography,
} from "@mui/material";
import { Menu } from "@mui/icons-material";

import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Keeper - Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar/>
      </header>

    </div>
  );
}
